embedding_size: 64
feat_embed_dim: 64

n_layers: 2
knn_k: 10
mm_image_weight: 0.1
valid_metric: 'Recall@20'
weight_size: [64, 64]
lambda_coeff: 0.9
dropout: 0.0
stopping_step: 10

n_mm_layers: 1
gamma: [0.5, 0.9]
n_ui_layers: [3, 4]
min_sim: 0.0
max_sim: [0.8, 1.0]
alpha: [0.1, 0.5, 0.9]
weight_decay: [0, 1e-6]

hyper_parameters: ["n_ui_layers", "gamma", "max_sim", "alpha", "weight_decay"]